# 财经数据监控系统配置文件

# 刷新间隔（秒）
refresh_interval: 15

# 显示模式
# 0: 仅显示高重要性
# 1: 显示所有数据
# 2: 显示高重要性+利率信息
# 3: 显示高重要性+重要事件
default_display_mode: 0

# 界面设置
ui:
  # 时间列宽度
  time_width: 6
  # 重要性列宽度
  importance_width: 4
  # 数值列宽度（前值、预测、公布值）
  value_width: 12
